version: '3.5'
services:
  swagger-ui:
    image: swagger-ui:1.0.0
    container_name: swagger-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    ports:
      - "3000:3000"
    restart: always
